version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - govuk-pay
      - docker
