workspace:
  base: /workdir

pipeline:

  build_image:
    image: docker:17.07.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - ls -alh /workdir/src/github.com/UKHomeOffice/
    when:
      event: [pull_request, push, tag]

  push_image:
    image: docker:17.07.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_IMAGE=nginx-proxy
      - DOCKER_REPO=artifactory-internal.digital.homeoffice.gov.uk
      - DOCKER_BASEDIR=/
      - DOCKER_USERNAME=lev-web-robot
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" "${DOCKER_REPO}"
      - ./publish.sh "ngx" "${DOCKER_REPO}${DOCKER_BASEDIR}${DOCKER_IMAGE}" "${DRONE_TAG}"
    when:
      event: tag

  push_image_to_quay:
    image: docker:17.07.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_IMAGE=nginx-proxy
      - DOCKER_REPO=quay.io
      - DOCKER_BASEDIR=/ukhomeofficedigital/
      - DOCKER_USERNAME=ukhomeofficedigital+nginx_proxy
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_QUAY_PASSWORD}" "${DOCKER_REPO}"
      - ./publish.sh "ngx" "${DOCKER_REPO}${DOCKER_BASEDIR}${DOCKER_IMAGE}" "${DRONE_TAG}"
    when:
      event: tag

