workspace:
  base: /workdir

pipeline:
  build_image:
    image: docker:17.12.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t ngx:$${DRONE_COMMIT_SHA} .
    when:
      event: tag

  test_image:
    image: quay.io/ukhomeofficedigital/centos-base:v0.5.7
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - yum update -y
      - yum install -y -q docker openssl wget
      - ./ci-build.sh
    when:
      event: [pull_request, push]

  artifactory_build_tag:
    image: docker:17.12.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="docker-nginx-proxy-robot" -p=$${DOCKER_PASSWORD} artifactory-internal.digital.homeoffice.gov.uk
      - docker tag ngx:$${DRONE_COMMIT_SHA} artifactory-internal.digital.homeoffice.gov.uk/nginx-proxy:$${DRONE_TAG}
      - docker push artifactory-internal.digital.homeoffice.gov.uk/nginx-proxy:$${DRONE_TAG}
    when:
      event: tag

  quay_build_tag:
    image: docker:17.12.0
    secrets:
      - docker_quay_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+nginx_proxy" -p=$${DOCKER_QUAY_PASSWORD} quay.io
      - docker tag ngx:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/nginx-proxy:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/nginx-proxy:$${DRONE_TAG}
    when:
      event: tag
